version: '3.2'

services:

  api-gateway-service:
    container_name: ethertix-api-gateway-service
    image: sabin2000/ethertix-api-gateway-service
  
    build:
      context: ../backend/services/api-gateway
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5412:5412"

    volumes:
      - /app/node_modules
      - ../backend/services/api-gateway:/app

    networks:
      - my-service-network

  auth-service:
    container_name: ethertix-auth-service
    image: sabin2000/ethertix-auth-service

    build:
      context: ../backend/services/authentication
      dockerfile: Dockerfile

    networks:
      - ethertix-network
      - auth-service-network
    
    restart: always

    ports:
      - "5299:5299"
      
    volumes:
       - /app/node_modules
       - ../backend/services/authentication:/app

  events-service:
      container_name: ethertix-events-service
      image: sabin2000/ethertix-events-service
      build:
        context: ../backend/services/events
        dockerfile: Dockerfile

      restart: always

      ports:
        - "5301:5301"

      volumes:
        - /app/node_modules
        - ../backend/services/events:/app

      networks:
        - my-service-network
  
  categories-service:
      container_name: ethertix-categories-service
      image: sabin2000/ethertix-categories-service
      build:
        context: ../backend/services/categories
        dockerfile: Dockerfile

      restart: always

      ports:
        - "5300:5300"

      volumes:
        - /app/node_modules
        - ../backend/services/categories:/app

  venues-service:
    container_name: ethertix-venues-service
    image: sabin2000/ethertix-venues-service
    build:
      context: ../backend/services/venues
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5302:5302"

    volumes:
        - /app/node_modules
        - ../backend/services/venues:/app

    networks:
      - my-service-network
  
  tickets-service: ## Tickets Service Configuration
    container_name: ethertix-tickets-service
    image: sabin2000/ethertix-tickets-service

    build:
      context: ../backend/services/tickets
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5303:5303"

    volumes:
        - /app/node_modules
        - ../backend/services/tickets:/app

    networks:
      - my-service-network

  discount-service:

    container_name: ethertix-discounts-service
    image: sabin2000/ethertix-discount-service

    build:
      context: ../backend/services/discount
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5304:5304"

    volumes:
        - /app/node_modules
        - ../backend/services/discount:/app

    networks:
      - my-service-network
  database-service:
    image: mongo

    ports:
      - "27017:27017"

    restart: always

    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
        
volumes:
  mongodb_data_volume:

networks:
  my-service-network:
    driver: bridge
    external: true

  auth-service-network:
    external: true