version: '3.2'

services:

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - auth-api:auth-api

    network_mode: host

  auth-service:
    container_name: auth-service
    image: sabin2000/ethertix-auth-service
    build:
      context: ../backend/services/authentication
      dockerfile: Dockerfile
    
    restart: always

    ports:
      - "5299:5299"
      
    volumes:
       - /app/node_modules
       - ../backend/services/authentication:/app
  auth-tests: # Tests Service
    build:
      context: ../backend/services/authentication
      dockerfile: Dockerfile
      
    volumes:
      - /app/node_modules

    command: ["npm", "run", "auth:test"]

  events-service:
      container_name: events-api
      image: sabin2000/ethertix-events-service
      build:
        context: ../backend/services/events
        dockerfile: Dockerfile

      restart: always

      ports:
        - "5301:5301"

      volumes:
        - /app/node_modules
        - ../backend/services/events:/app
  
  categories-service:
      container_name: categories-api
      image: sabin2000/ethertix-categories-service
      build:
        context: ../backend/services/categories
        dockerfile: Dockerfile

      restart: always

      ports:
        - "5300:5300"

      volumes:
        - /app/node_modules
        - ../backend/services/categories:/app

  venues-service:
    container_name: venues-api
    image: sabin2000/ethertix-venues-service
    build:
      context: ../backend/services/venues
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5302:5302"

    volumes:
        - /app/node_modules
        - ../backend/services/venues:/app
  
  tickets-service:
    container_name: tickets-api
    image: sabin2000/ethertix-tickets-service

    build:
      context: ../backend/services/tickets
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5303:5303"

    volumes:
        - /app/node_modules
        - ../backend/services/tickets:/app

  discount-service:

    container_name: discount-service
    image: sabin2000/ethertix-discount-service

    build:
      context: ../backend/services/discount
      dockerfile: Dockerfile

    restart: always

    ports:
      - "5304:5304"

    volumes:
        - /app/node_modules
        - ../backend/services/discount:/app
  database-service:
    image: mongo

    ports:
      - "27017:27017"

    restart: always

    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
volumes:
  mongodb_data_volume: