name: Authentication Service Deployment

on:
  push:
    branches: [master]

jobs:

  build-auth-service:

    runs-on: self-hosted

    steps:

      - name: Get Auth Code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3

        with:
          node-version: 18