name: Events Service Deployment

on:

  push:
    branches: [master]

jobs:
  build-auth-service:

    runs-on: self-hosted

    steps:
    
      - uses: actions/checkout@v2

      - name: Build / Deploy Available Events Service
        run:
          |