name: Tickets Service Deployment

on:

  push:
    branches:
      - "master"

jobs:

  build-auth-service:

    runs-on: self-hosted

    steps:

      - name: Get Auth Code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3

      - name: Install Tickets Dependencies
        run: npm install

      - name: Build Tickets Service
        run: npm run build

        with:
          node-version: 18