  version: '3.3'

  services:
  
    zookeeper:
      
        image: zookeeper:3.6

        ports:
          - "2181:2181"

    kafka-client:
      image: node:alpine
      working_dir: /app

      environment:
        KAFKA_BROKERS: "kafka:9092"
        KAFKA_TOPIC: "my-auth-topic"

      volumes:
        - ./app:/app

      depends_on:
        - kafka

    kafka:
      image: wurstmeister/kafka
      
      ports:
        - "9092:9092"

      environment:
        KAFKA_HOST_NAME: localhost
        KAFKA_PORT: 9092
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
        KAFKA_LISTENERS: "PLAINTEXT://kafka:9092"
        KAFKA_CREATE_TOPICS: "my-topic:1:1"

      depends_on:
        - zookeeper