name: Events Backend Service CI/CD Deployment

on:

  push:
    branches:
      - "master"

jobs:

  build-auth-service:

    runs-on: self-hosted

    steps:

      - name: Get Events Code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3

      - name: Install Events Dependencies
        run: npm install

      - name: Build Events Service
        run: npm run build